name: shopping_list
description: A Shopping List app made in Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-178.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  custom_check_box: ^0.0.4
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.0
  firebase_auth: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
